import { type Metadata } from "next";
import { AppLayout } from "@/components/layout/AppLayout";
import { GlobalProvider } from "@/components/providers/GlobalProvider";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
      <AppLayout>
        {children}
      </AppLayout>
    </GlobalProvider>
  );
}
