services: 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: "unless-stopped"
    volumes:
      - local_redis_data:/root/redis
    networks:
      - speechie-api

volumes:
  local_redis_data:
    driver: local

networks:
  speechie-api:
    driver: bridge